### ISSUE TITLE
BGO替换文件开启60帧可行吗

### ISSUE THREAD

**Issue by Kaleidoblood** [nishuoshenme/FGOFPSUnlocker#10]
最近换机了，华为的没法解BL锁所以就没有办法刷magisk，不知道日服那种替换文件开启60帧的方法在国服可行吗

**Comment by nishuoshenme** [comment]
> 最近换机了，华为的没法解BL锁所以就没有办法刷magisk，不知道日服那种替换文件开启60帧的方法在国服可行吗

要等一年后更新引擎

**Comment by Kaleidoblood** [comment]
> > 最近换机了，华为的没法解BL锁所以就没有办法刷magisk，不知道日服那种替换文件开启60帧的方法在国服可行吗
> 
> 不行，要等一年后更新引擎。再说替换文件也要root权限

那可以通过修改安装包来实现60帧吗？

**Comment by nishuoshenme** [comment]
> > > 最近换机了，华为的没法解BL锁所以就没有办法刷magisk，不知道日服那种替换文件开启60帧的方法在国服可行吗
> > 
> > 
> > 不行，要等一年后更新引擎。再说替换文件也要root权限
> 
> 那可以通过修改安装包来实现60帧吗？

有签名验证的

**Comment by Kaleidoblood** [comment]
> > > > 最近换机了，华为的没法解BL锁所以就没有办法刷magisk，不知道日服那种替换文件开启60帧的方法在国服可行吗
> > > 
> > > 
> > > 不行，要等一年后更新引擎。再说替换文件也要root权限
> > 
> > 
> > 那可以通过修改安装包来实现60帧吗？
> 
> 有签名验证的

好的 ，谢谢解答
